>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
>>> lazy_matrix_mul()
Traceback (most recent call last):
	...
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
>>> lazy_matrix_mul([[3]],)
Traceback (most recent call last):
	...
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'
>>> lazy_matrix_mul(True, [[3]])
Traceback (most recent call last):
	...
ValueError: Scalar operands are not allowed, use '*' instead
>>> lazy_matrix_mul([[3]], "False")
Traceback (most recent call last):
	...
ValueError: Scalar operands are not allowed, use '*' instead
>>> lazy_matrix_mul([1, 2, 3], [[4, 5, 6]])
Traceback (most recent call last):
	...
ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)
>>> lazy_matrix_mul([[1, 2, 3]], [4, 5, 6])
array([32])
>>> lazy_matrix_mul([[]], [[1, 2, 3]])
Traceback (most recent call last):
	...
ValueError: shapes (1,0) and (1,3) not aligned: 0 (dim 1) != 1 (dim 0)
>>> lazy_matrix_mul([[3]], [])
Traceback (most recent call last):
	...
ValueError: shapes (1,1) and (0,) not aligned: 1 (dim 1) != 0 (dim 0)
>>> lazy_matrix_mul([[1, 2, '3']], [[1], [2], [3]])
Traceback (most recent call last):
	...
TypeError: invalid data type for einsum
>>> lazy_matrix_mul([[1, 2, 3]], [[1], [2], ['a']])
Traceback (most recent call last):
	...
TypeError: invalid data type for einsum
>>> lazy_matrix_mul([[1, 2, 3], [3]], [[1], [2], [3]])
Traceback (most recent call last):
	...
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[1, 2, 3]], [[1, 3], [2], [3]])
Traceback (most recent call last):
	...
ValueError: setting an array element with a sequence.
>>> lazy_matrix_mul([[1, 2, 3]], [[1], [2], [3], [4]])
Traceback (most recent call last):
	...
ValueError: shapes (1,3) and (4,1) not aligned: 3 (dim 1) != 4 (dim 0)
